name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Se activa cuando haces push a `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install  # o `yarn install`

      - name: Build project
        run: npm run build  # o el comando que uses para construir (ej: `yarn build`)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Cambia esto según tu carpeta de construcción (ej: `build`, `public`, etc.)